//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaTicketes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketSellerEntities : DbContext
    {
        public TicketSellerEntities()
            : base("name=TicketSellerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TicketsHorarios> TicketsHorarios { get; set; }
        public virtual DbSet<TicketsLugares> TicketsLugares { get; set; }
        public virtual DbSet<TicketsRuta> TicketsRuta { get; set; }
        public virtual DbSet<TickersSale> TickersSale { get; set; }
    }
}
